### ISSUE TITLE
CiviCRM composer compile tasks fail with composer 2

### ISSUE THREAD

**Issue by jackrabbithanna** [civicrm/composer-compile-lib#3]
Using CiviCRM 5.39
Included patch mentioned in https://github.com/civicrm/composer-compile-lib/issues/2

CiviCRM compile tasks work with Composer 1, but not composer 2
Both of CiviCRM's compile tasks generate this warning:
WARNING: Failed to read compilation-task from COMPOSER_COMPILE_TASK. Please use "composer compile".

```
jackrabbithanna@jackrabbithanna-HP-EliteBook-840-G1:/var/www/html/distro9.skvare.com$ ./vendor/bin/composer compile

The following packages have new compilation tasks:
 - civicrm/composer-compile-lib has 1 task
 - civicrm/civicrm-core has 1 task

Allow these packages to compile? ([y]es, [a]lways, [n]o, [l]ist, [h]elp) y
Compiling additional files (For full details, use verbose "-v" mode.)
Compile: Generate CCL wrapper functions
WARNING: Failed to read compilation-task from COMPOSER_COMPILE_TASK. Please use "composer compile".
Compile: Greenwich CSS (dist/bootstrap3.css)
WARNING: Failed to read compilation-task from COMPOSER_COMPILE_TASK. Please use "composer compile".
WARNING: Failed to read compilation-task from COMPOSER_COMPILE_TASK. Please use "composer compile".
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid task: required argument 'scss-files' is missing in /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks/Scss.php:36
Stack trace:
#0 /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks.php(15): CCL\Tasks\Scss::compile(Array)
#1 Command line code(1): CCL\Tasks::scss(Array)
#2 {main}
  thrown in /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks/Scss.php on line 36
> @php -r 'require_once '\''/var/www/html/distro9.skvare.com/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL::copy('\''../../bower_components/select2/select2-bootstrap.css'\'', '\''extern/select2/select2-bootstrap.scss'\'');'
> @php -r 'require_once '\''/var/www/html/distro9.skvare.com/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);'
Script @php -r 'require_once '\''/var/www/html/distro9.skvare.com/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::scss($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);' handling the shell-runner event returned with error code 255
```
composer version:
```
jackrabbithanna@jackrabbithanna-HP-EliteBook-840-G1:/var/www/html/distro9.skvare.com$ ./vendor/bin/composer --version
Composer 2.1.8 2021-09-15 13:55:14
```
Open to suggestions if anyone recognizes this warning, missing the COMPOSER_COMPILE_TASK global variable

**Comment by jackrabbithanna** [comment]
Sorry was diagnosing, this set of errors would appear first:
```
[PHP Fatal error:  Uncaught InvalidArgumentException: Invalid file reference (tpl-file=NULL) in /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php:65
Stack trace:
#0 /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php(24): CCL\Tasks\Template::assertFileField(Array, 'tpl-file')
#1 /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks.php(24): CCL\Tasks\Template::compile(Array)
#2 Command line code(1): CCL\Tasks::template(Array)
#3 {main}
  thrown in /var/www/html/distro9.skvare.com/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php on line 65
> @php -r 'require_once '\''/var/www/html/distro9.skvare.com/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::template($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);'
Script @php -r 'require_once '\''/var/www/html/distro9.skvare.com/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::template($GLOBALS[\Civi\CompilePlugin\TaskTransfer::GLOBAL_VAR]);' handling the shell-runner event returned with error code 255
](url)
```
I had gotten into ./src/Template.php compile() and added a if (empty($tasks)) return ..
which led to the error in my first comment.
